### ISSUE TITLE
Getting ESLint & Prettier to work with this project

### ISSUE THREAD

**Issue by qodesmith** [markhker/react-from-scratch#1]
Hello! First, thank you for the time you put into the [blog post](https://marlom.dev/advanced-react-and-webpack-configuration) and this project. I found this repo as a result of that post.

Question for you... I'm using VSCode. Do you need to install the ESLint and Prettier plugins for VSCode in order for these to work? I'm new to these tools (although I know what they do) and I've not set them up before. I was under the impression that since we installed all these packages as part of the project itself, one wouldn't need the VSCode packages for them to kick in.

I cloned this repo, ran `npm i` (which I had to do `npm i --force` because of mismatched peer deps), and spun up the project with `npm start`. I purposely added some extra spaces in the JSX but there was no linting or auto-fixing of styling issues when I saved the file. Once I installed the VSCode plugins, linting started to work but prettier wouldn't automatically fix changes on save. I'm curious if you've experienced the same on your end or how you've got things setup. Thank you!

**Comment by markhker** [comment]
@qodesmith Thanks for the feedback
Yes I always struggle with those integrations. I just follow these instructions rom the great Wes Bos: https://github.com/wesbos/eslint-config-wesbos#with-vs-code 
Hope it helps.

Also just added typescript to the mix.
